# Generated by Django 2.0.10 on 2020-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0, help_text="User's reputation based on the rides taken and offered."),
        ),
    ]
